services:
  - type: web
    name: easybus
    env: node
    buildCommand: npm install && cd client && set "REACT_APP_API_BASEURL=/api" && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && NODE_ENV=production npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # This will prompt you to add this as a secret in Render dashboard
      - key: JWT_SECRET
        sync: false # This will prompt you to add this as a secret in Render dashboard
      - key: REFRESH_TOKEN_SECRET
        sync: false # Add this for token refresh functionality
      - key: ADMIN_EMAIL
        sync: false # Admin configuration
      - key: ADMIN_PASSWORD
        sync: false
      - key: EMAIL_HOST
        sync: false # Email configuration 
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
